`define mux_conf(mux_width) ($clog2(mux_width))
`define lut_conf(lut_width) (2 ** lut_width)
`define le_conf(lut_width) (`lut_conf(lut_width) + 1)
`define sb_le_conf(ic_pairs, cluster) (`mux_conf(ic_pairs * 4 + cluster))
`define sb_les_conf(ic_pairs, cluster, lut_size) (`sb_le_conf(ic_pairs, cluster) * cluster * lut_size)
`define sb_ic_conf(cluster) (`mux_conf(3 + cluster))
`define sb_ics_conf(ic_pairs, cluster) (ic_pairs * `sb_ic_conf(cluster))
`define sb_conf(ic_pairs, cluster, lut_size) (`sb_les_conf(ic_pairs, cluster, lut_size) + `sb_ics_conf(ic_pairs, cluster) * 4)
`define lt_conf(ic_pairs, cluster, lut_size) (`sb_conf(ic_pairs, cluster, lut_size) + `le_conf(lut_size) * cluster)