name: Run flow

on:    
  push:
    branches: [ "main" ]
    
jobs:
  build:
    strategy:
      matrix:
        platform: ["nangate45", "sky130hd", "sky130hs"]
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Run flow
        run: make ${{ matrix.os }}
      - 
        name: 'Upload results'
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ matrix.os }}
          path: out/results/${{ matrix.os }}
          retention-days: 7
      - 
        name: 'Upload reports'
        uses: actions/upload-artifact@v3
        with:
          name: reports-${{ matrix.os }}
          path: out/reports/${{ matrix.os }}
          retention-days: 7
      - 
        name: 'Upload logs'
        uses: actions/upload-artifact@v3
        with:
          name: logs-${{ matrix.os }}
          path: out/logs/${{ matrix.os }}
          retention-days: 7
